version: '3.8'

services:
  sunflower-bot:
    build: .
    container_name: sunflower_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ANONYMIZED_TELEMETRY=false
    volumes:
      - ./config.json:/app/config.json
      - ./sunflower/hq:/app/sunflower/hq
      - ./sunflower/vault:/app/sunflower/vault
